# Generated by Django 4.0.2 on 2022-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('manager', models.CharField(max_length=60)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=120)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
